### ISSUE TITLE
Error output and waystones not working

### ISSUE THREAD

**Issue by vandon1** [SweetRazory/WaystonesPlus#1]
When a player crafts a waystone I get loads of error output and they are not able to click on the waystones to open the gui.

This server is running Paper version git-Paper-54 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 8582999)
You are running the latest version
Previous version: git-Paper-49 (MC: 1.20.1)

[10:51:12] [Server thread/INFO]: [WaystonesPlus] Loading server plugin WaystonesPlus v1.3.2
[10:51:34] [Server thread/INFO]: [WaystonesPlus] Enabling WaystonesPlus v1.3.2

These are the permissions I have set for them in luckperms
[11:07:19 INFO]: > waystonesplus.craft
[11:07:19 INFO]: > waystonesplus.interact
[11:07:19 INFO]: > waystonesplus.placewaystone
[11:07:19 INFO]: > waystonesplus.rename
[11:07:21 INFO]: > waystonesplus.teleport

I got this error after starting with 1.3.2 the first time:
[10:52:03] [Server thread/ERROR]: Tried to load unrecognized recipe: waystonesplus:d1f9daad-2b05-4e4e-b06c-257d5eaa8fed removed now.
[10:52:03] [Server thread/ERROR]: Tried to load unrecognized recipe: waystonesplus:d1f9daad-2b05-4e4e-b06c-257d5eaa8fed removed now.

And then on crafting:
[10:55:57] [Server thread/ERROR]: Could not pass event CraftItemEvent to WaystonesPlus v1.3.2
java.lang.ClassCastException: class org.bukkit.craftbukkit.v1_20_R1.inventory.CraftShapelessRecipe cannot be cast to class org.bukkit.inventory.ShapedRecipe (org.bukkit.craftbukkit.v1_20_R1.inventory.CraftShapelessRecipe and org.bukkit.inventory.ShapedRecipe are in unnamed module of loader java.net.URLClassLoader @2b05039f)
	at org.sweetrazory.waystonesplus.eventhandlers.OnWaystoneCraft.<init>(OnWaystoneCraft.java:13) ~[WaystonesPlus-1.3.2.jar:?]
	at org.sweetrazory.waystonesplus.memoryhandlers.EventController.onWaystoneCraft(EventController.java:29) ~[WaystonesPlus-1.3.2.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor383.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:git-Paper-54]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.1.jar:git-Paper-54]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.1.jar:git-Paper-54]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3198) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.1.jar:git-Paper-54]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1339) ~[paper-1.20.1.jar:git-Paper-54]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.20.1.jar:git-Paper-54]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1316) ~[paper-1.20.1.jar:git-Paper-54]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1309) ~[paper-1.20.1.jar:git-Paper-54]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1287) ~[paper-1.20.1.jar:git-Paper-54]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1175) ~[paper-1.20.1.jar:git-Paper-54]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-54]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

[10:57:18] [Server thread/ERROR]: Could not pass event CraftItemEvent to WaystonesPlus v1.3.2
java.lang.ClassCastException: class org.bukkit.craftbukkit.v1_20_R1.inventory.CraftShapelessRecipe cannot be cast to class org.bukkit.inventory.ShapedRecipe (org.bukkit.craftbukkit.v1_20_R1.inventory.CraftShapelessRecipe and org.bukkit.inventory.ShapedRecipe are in unnamed module of loader java.net.URLClassLoader @2b05039f)
	at org.sweetrazory.waystonesplus.eventhandlers.OnWaystoneCraft.<init>(OnWaystoneCraft.java:13) ~[WaystonesPlus-1.3.2.jar:?]
	at org.sweetrazory.waystonesplus.memoryhandlers.EventController.onWaystoneCraft(EventController.java:29) ~[WaystonesPlus-1.3.2.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor383.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:git-Paper-54]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.1.jar:git-Paper-54]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.1.jar:git-Paper-54]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3198) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.1.jar:git-Paper-54]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1339) ~[paper-1.20.1.jar:git-Paper-54]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.20.1.jar:git-Paper-54]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1316) ~[paper-1.20.1.jar:git-Paper-54]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1309) ~[paper-1.20.1.jar:git-Paper-54]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1287) ~[paper-1.20.1.jar:git-Paper-54]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1175) ~[paper-1.20.1.jar:git-Paper-54]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-54]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[10:58:38] [Server thread/ERROR]: Could not pass event BlockPlaceEvent to WaystonesPlus v1.3.2
java.lang.NullPointerException: null
	at java.util.Objects.requireNonNull(Objects.java:209) ~[?:?]
	at org.sweetrazory.waystonesplus.memoryhandlers.WaystoneMemory.addWaystone(WaystoneMemory.java:70) ~[WaystonesPlus-1.3.2.jar:?]
	at org.sweetrazory.waystonesplus.eventhandlers.PlayerInteractListener.addWaystoneAndNotify(PlayerInteractListener.java:85) ~[WaystonesPlus-1.3.2.jar:?]
	at org.sweetrazory.waystonesplus.eventhandlers.PlayerInteractListener.onBlockPlace(PlayerInteractListener.java:77) ~[WaystonesPlus-1.3.2.jar:?]
	at org.sweetrazory.waystonesplus.memoryhandlers.EventController.onBlockPlace(EventController.java:39) ~[WaystonesPlus-1.3.2.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor379.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:git-Paper-54]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.1.jar:git-Paper-54]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.1.jar:git-Paper-54]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:416) ~[paper-1.20.1.jar:git-Paper-54]
	at net.minecraft.world.item.ItemStack.useOn(ItemStack.java:412) ~[paper-1.20.1.jar:git-Paper-54]
	at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:599) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1960) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:37) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.1.jar:git-Paper-54]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1339) ~[paper-1.20.1.jar:git-Paper-54]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.20.1.jar:git-Paper-54]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1316) ~[paper-1.20.1.jar:git-Paper-54]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1309) ~[paper-1.20.1.jar:git-Paper-54]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1287) ~[paper-1.20.1.jar:git-Paper-54]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1175) ~[paper-1.20.1.jar:git-Paper-54]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-54]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by vandon1** [comment]
Please let me know if you need any additional information

**Comment by SweetRazory** [comment]
@vandon1 (I forgot to tag you)

**Comment by vandon1** [comment]
I'll try a fresh server and add them back in one by one, unless there's a known issue with any of these below.

[12:25:47] [Server thread/INFO]: Server Plugins (34):
[12:25:47] [Server thread/INFO]: Bukkit Plugins:
[12:25:47] [Server thread/INFO]:  - AureliumSkills, ChestSort, dynmap, Dynmap-EssentialsX, EnderDragonTweaks, Essentials, EssentialsAntiBuild, EssentialsChat, EssentialsDiscord, floodgate
[12:25:47] [Server thread/INFO]:  Graves, HolographicDisplays, IronElevators, LuckPerms, MapModCompanion, NBTAPI, NoChatReports, NoEnderChest, NotTooExpensive, PetLives
[12:25:47] [Server thread/INFO]:  PlaceholderAPI, Playtimes, ProtocolLib, SkinsRestorer, spark, TreeFeller, VariableTime, Vault, ViaBackwards, ViaVersion

**Comment by SweetRazory** [comment]
Hey, I managed to find out that Vault is making WaystonePlus crash at start, I will look into what's causing the problem, but I cant really imagine :D

**Comment by SweetRazory** [comment]
Oh actually it isn't, at least I found out I need to add Multiversecore as a softrequirement

**Comment by vandon1** [comment]
Ok, fresh server... luckperms is the only other plugin because I needed permissions.
I don't get an error on crafting, but I do still get one when I place it. Right or left clicking doesn't activate anything either.
These permissions are active:
- waystonesplus.craft
- waystonesplus.interact
- waystonesplus.placewaystone
- waystonesplus.rename
- waystonesplus.teleport

In case it matters running latest java for windows 10 64bit
openjdk version "17.0.7" 2023-04-18
OpenJDK Runtime Environment Temurin-17.0.7+7 (build 17.0.7+7)
OpenJDK 64-Bit Server VM Temurin-17.0.7+7 (build 17.0.7+7, mixed mode, sharing)

[15:54:52] [Server thread/INFO]: Preparing level "JavaRockS7"
[15:55:04] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[15:55:04] [Server thread/INFO]: Time elapsed: 54 ms
[15:55:04] [Server thread/INFO]: Preparing start region for dimension minecraft:the_nether
[15:55:04] [Server thread/INFO]: Time elapsed: 39 ms
[15:55:04] [Server thread/INFO]: Preparing start region for dimension minecraft:the_end
[15:55:04] [Server thread/INFO]: Time elapsed: 37 ms
[15:55:04] [Server thread/INFO]: [WaystonesPlus] Enabling WaystonesPlus v1.3.2
[15:55:04] [Server thread/INFO]: §aThe 'waystones' folder has been created.
[15:55:04] [Server thread/INFO]: Running delayed init tasks
[15:55:04] [Server thread/INFO]: Done (16.317s)! For help, type "help"
[15:55:04] [Server thread/INFO]: Timings Reset
[15:55:15] [Server thread/INFO]: There are 2 data pack(s) enabled: [vanilla (built-in)], [file/bukkit (world)]
[15:55:15] [Server thread/INFO]: There are no more data packs available
[15:55:18] [Server thread/INFO]: Server Plugins (2):
[15:55:18] [Server thread/INFO]: Bukkit Plugins:
[15:55:18] [Server thread/INFO]:  - LuckPerms, WaystonesPlus
[15:55:20] [Server thread/INFO]: Checking version, please wait...
[15:55:21] [Thread-6/INFO]: This server is running Paper version git-Paper-54 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 8582999)
You are running the latest version
Previous version: git-Paper-49 (MC: 1.20.1)

[15:57:55] [Server thread/ERROR]: Could not pass event BlockPlaceEvent to WaystonesPlus v1.3.2
java.lang.NullPointerException: null
	at java.util.Objects.requireNonNull(Objects.java:209) ~[?:?]
	at org.sweetrazory.waystonesplus.memoryhandlers.WaystoneMemory.addWaystone(WaystoneMemory.java:70) ~[WaystonesPlus-1.3.2.jar:?]
	at org.sweetrazory.waystonesplus.eventhandlers.PlayerInteractListener.addWaystoneAndNotify(PlayerInteractListener.java:85) ~[WaystonesPlus-1.3.2.jar:?]
	at org.sweetrazory.waystonesplus.eventhandlers.PlayerInteractListener.onBlockPlace(PlayerInteractListener.java:77) ~[WaystonesPlus-1.3.2.jar:?]
	at org.sweetrazory.waystonesplus.memoryhandlers.EventController.onBlockPlace(EventController.java:39) ~[WaystonesPlus-1.3.2.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor17.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:git-Paper-54]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.1.jar:git-Paper-54]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.1.jar:git-Paper-54]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:416) ~[paper-1.20.1.jar:git-Paper-54]
	at net.minecraft.world.item.ItemStack.useOn(ItemStack.java:412) ~[paper-1.20.1.jar:git-Paper-54]
	at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:599) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1960) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:37) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.1.jar:git-Paper-54]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1339) ~[paper-1.20.1.jar:git-Paper-54]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.20.1.jar:git-Paper-54]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1316) ~[paper-1.20.1.jar:git-Paper-54]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1309) ~[paper-1.20.1.jar:git-Paper-54]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1287) ~[paper-1.20.1.jar:git-Paper-54]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1175) ~[paper-1.20.1.jar:git-Paper-54]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-54]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by vandon1** [comment]
Just tried also removing luckperms too and only have waystonesplus and op'd myself. Still get an error on placing and cannot click the head. It never changes to what the picture looks like on the download page.
If you have a version with extra debugging turned on, I'll run that if you think it would help

**Comment by SweetRazory** [comment]
I posted some updates on Spigot this afternoon, the version you're using is 1.3.2, and I think in that version some of the permissions were broken, you should check it out, maybe it eliminates some errors. (I will reply on Buy me a Coffee in a moment, but I also want to thank you here for the support! <3)

**Comment by SweetRazory** [comment]
Oooooooh, one minute and maybe i can reproducate the error. And if I'm right, I already fixed it

**Comment by SweetRazory** [comment]
@vandon1 I reproduced the errors on the 1.3.2, and noticed the craft issue on 1.3.5 (latest) fixing it, I will tag you again when 1.3.6 is uploaded, and ready for testing (Also I'm testing it on the same server file as you)

**Comment by vandon1** [comment]
1.3.5 worked! However, even op'd I could not take the New Waystone out of the crafting grid.  I had to have luckperms installed and still had to deop myself before it would take it out. When placing, it now makes the statue thing and there was no error. 
And it continues to work with all the plugins re-enabled.  And it works on the original server! Renaming on an anvil is glitchy tho, you have to backspace slowly but it does work. Breaking with the break permission still causes an error:

[16:57:23] [Server thread/ERROR]: Could not pass event BlockBreakEvent to WaystonesPlus v1.3.5
java.lang.NullPointerException: Cannot invoke "org.sweetrazory.waystonesplus.waystone.Waystone.getName()" because the return value of "java.util.Map.get(Object)" is null
	at org.sweetrazory.waystonesplus.eventhandlers.OnWaystoneBreak.<init>(OnWaystoneBreak.java:29) ~[WaystonesPlus-1.3.5.jar:?]
	at org.sweetrazory.waystonesplus.memoryhandlers.EventController.onWaystoneBreak(EventController.java:44) ~[WaystonesPlus-1.3.5.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor381.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:git-Paper-54]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.1.jar:git-Paper-54]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.1.jar:git-Paper-54]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.level.ServerPlayerGameMode.destroyBlock(ServerPlayerGameMode.java:378) ~[?:?]
	at net.minecraft.server.level.ServerPlayerGameMode.destroyAndAck(ServerPlayerGameMode.java:337) ~[?:?]
	at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:215) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1872) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:42) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.a(ServerboundPlayerActionPacket.java:15) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.1.jar:git-Paper-54]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1339) ~[paper-1.20.1.jar:git-Paper-54]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.20.1.jar:git-Paper-54]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1316) ~[paper-1.20.1.jar:git-Paper-54]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1309) ~[paper-1.20.1.jar:git-Paper-54]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1287) ~[paper-1.20.1.jar:git-Paper-54]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1175) ~[paper-1.20.1.jar:git-Paper-54]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-54]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[16:57:25] [Server thread/ERROR]: Could not pass event BlockBreakEvent to WaystonesPlus v1.3.5
java.lang.NullPointerException: Cannot invoke "org.sweetrazory.waystonesplus.waystone.Waystone.getName()" because the return value of "java.util.Map.get(Object)" is null
	at org.sweetrazory.waystonesplus.eventhandlers.OnWaystoneBreak.<init>(OnWaystoneBreak.java:29) ~[WaystonesPlus-1.3.5.jar:?]
	at org.sweetrazory.waystonesplus.memoryhandlers.EventController.onWaystoneBreak(EventController.java:44) ~[WaystonesPlus-1.3.5.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor381.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:git-Paper-54]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.1.jar:git-Paper-54]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.1.jar:git-Paper-54]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.level.ServerPlayerGameMode.destroyBlock(ServerPlayerGameMode.java:378) ~[?:?]
	at net.minecraft.server.level.ServerPlayerGameMode.destroyAndAck(ServerPlayerGameMode.java:337) ~[?:?]
	at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:215) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1872) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:42) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.a(ServerboundPlayerActionPacket.java:15) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.1.jar:git-Paper-54]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1339) ~[paper-1.20.1.jar:git-Paper-54]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.20.1.jar:git-Paper-54]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1316) ~[paper-1.20.1.jar:git-Paper-54]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1309) ~[paper-1.20.1.jar:git-Paper-54]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1287) ~[paper-1.20.1.jar:git-Paper-54]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1175) ~[paper-1.20.1.jar:git-Paper-54]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-54]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by SweetRazory** [comment]
@vandon1 I did some fixing around, the permissions/opcheck were a little off. Can you test 1.3.6? I just published it.

**Comment by SweetRazory** [comment]
*Remove the WaystonePlus plugin folder before testing

**Comment by SweetRazory** [comment]
Btw I couldn't be more grateful for you helping me solving these problems, I can't imagine how many users tried it out and got let down by the plugin not working :/

**Comment by vandon1** [comment]
np, its one of the only ones that actually supports 1.20.1
So, 1.3.6 seems to work and op permissions work. The blockbreakevent error is still there.
I crafted a waystone, renamed it, and placed it more than 50 blocks away from where I was, crafted and then repeated in a different direction checking the interact gui each time. It didnt save the first one named test and it wasnt visible from any other waystones. It saved "river" and "other ways" (#2 and #3) but it wont save any more. I created "number 3" and "number 4" and placed them at least 50-60 blocks away and while they work for interact, each will only show "river"(the first one that actually saved in the waystones directory and I can teleport to river. From river, I can only see "other ways" but no other waystones.
Sorry for the rambling explanation.

**Comment by SweetRazory** [comment]
I'm going to test it with a clean server, special world name (not world, which is default), operator, paper 54 build.
Until then, can I ask if you get a blockbreakevent error when you want to break a newly placed waystone? @vandon1

**Comment by SweetRazory** [comment]
(Btw if you're OP, the 50 block distance is not applying to you anymore)

**Comment by SweetRazory** [comment]
Yeah I'm noticing the menu stuff definietly

**Comment by vandon1** [comment]
It seems like now there's no error on breaking and the new waystones are placing and saving correctly. The only change was I stopped my test server and had to restart it after my first set of tests.
The waystones that didnt save are still there, but if you break them it just breaks the decoration blocks(lodestone and slab) but the armorstand/smooth stone blocks stay visible but you cannot interact with it.
Maybe there's an initial setup it does when the plugin first starts but it doesnt get the right settings until you restart the server?

**Comment by SweetRazory** [comment]
Yeah, I havent came up with a solution to that. Maybe I just delete the Waystones from the world when the server shuts down, so when someone removes a config file, this doesnt happen, but yeah i have to implement a solution to that

Btw I get the menu stuff on the latest build, so until I cant find it and fix it, I wont call it a day

**Comment by SweetRazory** [comment]
Okay I think I found all of the errors mentioned above, and will be able to fix it, something is wrong with the crafting recipe and/or placing down the item crafted

**Comment by vandon1** [comment]
Just wiped the world and reset everything. I started, let the world gen and plugins init then stopped the world. I started again and logged in. Created a new waystone, renamed it and placed it. It crated a new guid folder and saved. I created another waystone and placed it. It did not save and it didnt show any other waystones when I clicked it.  I broke it and the folder for the first waystone disappeared and I also got a breakblockevent error:

[18:27:28] [Server thread/ERROR]: Could not pass event BlockBreakEvent to WaystonesPlus v1.3.6
java.lang.NullPointerException: Cannot invoke "org.sweetrazory.waystonesplus.waystone.Waystone.getName()" because the return value of "java.util.Map.get(Object)" is null
	at org.sweetrazory.waystonesplus.eventhandlers.OnWaystoneBreak.<init>(OnWaystoneBreak.java:28) ~[WaystonesPlus-1.3.6.jar:?]
	at org.sweetrazory.waystonesplus.memoryhandlers.EventController.onWaystoneBreak(EventController.java:44) ~[WaystonesPlus-1.3.6.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor379.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:git-Paper-54]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.1.jar:git-Paper-54]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.1.jar:git-Paper-54]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.level.ServerPlayerGameMode.destroyBlock(ServerPlayerGameMode.java:378) ~[?:?]
	at net.minecraft.server.level.ServerPlayerGameMode.destroyAndAck(ServerPlayerGameMode.java:337) ~[?:?]
	at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:301) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1872) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:42) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.a(ServerboundPlayerActionPacket.java:15) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.1.jar:git-Paper-54]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1339) ~[paper-1.20.1.jar:git-Paper-54]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.20.1.jar:git-Paper-54]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1316) ~[paper-1.20.1.jar:git-Paper-54]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1309) ~[paper-1.20.1.jar:git-Paper-54]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1287) ~[paper-1.20.1.jar:git-Paper-54]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1175) ~[paper-1.20.1.jar:git-Paper-54]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-54]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by vandon1** [comment]
Please dont neglect your school or real job. :)
I won't be able to do much more testing tonight and I'll be at work tomorrow during the day.

**Comment by SweetRazory** [comment]
Nah, It's okay :) I'm a freelancer entrepreneur, so I'm kind of my own boss in terms of timetable. Btw, I think the issue is I put the waystone's id before it's even places in the waystone spawn item, which gets saved in the server's memory, and every craft results having the same waystoneid. If placed, it creates the structure, and tries to save it to a config file, but can't because of the folder check etc. So what I have to do is make the spawn head only contain the type, and when placed, generate an ID there.

**Comment by SweetRazory** [comment]
I posted 1.3.7 on Spigot, now everything should work fine :D I didn't knew this recipe stuff, and it's so annoying, but yet so obvious @vandon1

**Comment by SweetRazory** [comment]
I should probably make a discord for bugreporting and general discussion, would make organising a hella lot easier

**Comment by vandon1** [comment]
Cleared world and reset everything, deleted waystones folder. Created and renamed first one "number 1" and placed, created folder. Created and renamed "number 2" placed and it made no folder and had no other waystones in the gui. Same for "number 3", placed and no folder, no other waystones in gui.  I'm headed to bed and will be able to do more testing tomorrow evening and Thursday.

[19:21:14] [Server thread/INFO]: [WaystonesPlus] Enabling WaystonesPlus v1.3.7
This was output when during the craft/rename/place, not sure which phase but I think it was during placing.

[19:25:44] [Server thread/INFO]: 1
[19:25:44] [Server thread/INFO]: 2
[19:25:44] [Server thread/INFO]: 3
[19:25:44] [Server thread/INFO]: 7
[19:25:44] [Server thread/INFO]: 8
[19:25:44] [Server thread/INFO]: 9
[19:25:44] [Server thread/INFO]: 10
[19:25:44] [Server thread/INFO]: 11
[19:25:44] [Server thread/INFO]: 12
[19:25:44] [Server thread/INFO]: 14
[19:25:44] [Server thread/INFO]: 15
[19:25:44] [Server thread/INFO]: 18
[19:25:44] [Server thread/INFO]: 19
[19:25:44] [Server thread/INFO]: 20
[19:25:44] [Server thread/INFO]: 21
[19:25:44] [Server thread/INFO]: 22
[19:25:44] [Server thread/INFO]: 23
[19:25:44] [Server thread/INFO]: 24
[19:25:44] [Server thread/INFO]: 25
[19:25:44] [Server thread/INFO]: 26
[19:25:44] [Server thread/INFO]: 27
[19:25:44] [Server thread/INFO]: 28
[19:25:44] [Server thread/INFO]: 29
[19:25:44] [Server thread/INFO]: 30
[19:25:44] [Server thread/INFO]: 31
[19:25:44] [Server thread/INFO]: 32
[19:25:44] [Server thread/INFO]: 33
[19:25:44] [Server thread/INFO]: 34
[19:25:44] [Server thread/INFO]: 35
[19:25:44] [Server thread/INFO]: 34
[19:25:44] [Server thread/INFO]: 35
[19:25:44] [Server thread/INFO]: 34
[19:25:44] [Server thread/INFO]: 35
[19:25:44] [Server thread/INFO]: 36
[19:25:44] [Server thread/INFO]: 37
[19:25:44] [Server thread/INFO]: 38
[19:25:44] [Server thread/INFO]: 39
[19:25:44] [Server thread/INFO]: 40
[19:25:44] [Server thread/INFO]: 41
[19:25:44] [Server thread/INFO]: 42
[19:25:44] [Server thread/INFO]: 43
[19:25:44] [Server thread/INFO]: 44
[19:25:44] [Server thread/INFO]: 45
[19:25:44] [Server thread/INFO]: 12
[19:25:44] [Server thread/INFO]: 14
[19:25:44] [Server thread/INFO]: 15
[19:25:44] [Server thread/INFO]: 16
[19:25:44] [Server thread/INFO]: 17
[19:27:28] [Server thread/INFO]: 1
[19:27:28] [Server thread/INFO]: 2
[19:27:28] [Server thread/INFO]: 3
[19:27:28] [Server thread/INFO]: 4
[19:27:28] [Server thread/INFO]: [WaystonesPlus] [STDOUT] org.sweetrazory.waystonesplus.waystone.Waystone@2e380ab5
[19:27:28] [Server thread/WARN]: Nag author(s): '[SweetRazory]' of 'WaystonesPlus v1.3.7' about their usage of System.out/err.print. Please use your plugin's logger instead (JavaPlugin#getLogger).
[19:27:28] [Server thread/INFO]: 7
[19:27:28] [Server thread/INFO]: 8
[19:27:28] [Server thread/INFO]: 9
[19:27:28] [Server thread/INFO]: 10
[19:27:28] [Server thread/INFO]: 11
[19:27:28] [Server thread/INFO]: 12
[19:27:28] [Server thread/INFO]: 14
[19:27:28] [Server thread/INFO]: 15
[19:27:28] [Server thread/INFO]: 16
[19:27:28] [Server thread/INFO]: 17
[19:27:28] [Server thread/INFO]: 12
[19:27:28] [Server thread/INFO]: 14
[19:27:28] [Server thread/INFO]: 15
[19:27:28] [Server thread/INFO]: 16
[19:27:28] [Server thread/INFO]: 17
[19:29:03] [Server thread/INFO]: 1
[19:29:03] [Server thread/INFO]: 2
[19:29:03] [Server thread/INFO]: 3
[19:29:03] [Server thread/INFO]: 4
[19:29:03] [Server thread/INFO]: [WaystonesPlus] [STDOUT] org.sweetrazory.waystonesplus.waystone.Waystone@2e380ab5
[19:29:03] [Server thread/INFO]: 7
[19:29:03] [Server thread/INFO]: 8
[19:29:03] [Server thread/INFO]: 9
[19:29:03] [Server thread/INFO]: 10
[19:29:03] [Server thread/INFO]: 11
[19:29:03] [Server thread/INFO]: 12
[19:29:03] [Server thread/INFO]: 14
[19:29:03] [Server thread/INFO]: 15
[19:29:03] [Server thread/INFO]: 16
[19:29:03] [Server thread/INFO]: 17
[19:29:03] [Server thread/INFO]: 12
[19:29:03] [Server thread/INFO]: 14
[19:29:03] [Server thread/INFO]: 15
[19:29:03] [Server thread/INFO]: 16
[19:29:03] [Server thread/INFO]: 17

**Comment by SweetRazory** [comment]
Oh shoot. 1 second.

**Comment by SweetRazory** [comment]
I uploaded the developement file, not the actual build by mistake

**Comment by SweetRazory** [comment]
Posted the actual build :D I will look into that rename stuff, if you dont find it in the 1.3.8 build. I'm heading to bed as well, it's 3am here :D

**Comment by vandon1** [comment]
1.4.0 looks like it saves all the waystones properly, renamed or not renamed and they show in the gui list.
However, even tho Im the one that placed the waystone and my uid is in the file, I still need the interact.private to interact with it when it's private. I can change it to global in the gui menu and then it works without interact.private/teleport.private but I can change it back private in the menu again and then without interact.private if I click on the waystone to doesnt do anything again.  So, we're nearly there lol

**Comment by SweetRazory** [comment]
I'm closing this thread due to fixing the bug, and continuing the discussion on discord.
